### ISSUE TITLE
[Feature Request] display average option on dice-roller (leading to pull request with more than just avg)

### ISSUE THREAD

**Issue by JYCasalis** [valentine195/obsidian-dice-roller#104]
Hi,

Let me start by stating how much I enjoy dice-roller and 5e-statblocks plugins!

As a personal challenge, I'm trying to make a custom layout for 5e-statblocks **in French**. I still have a looooong way to go but I'm enjoying the ride despite facing some issues along the way.

One of these issues is that you loose the automatic dice-roller integration when using Blocks configured to Render as Markdown. I am facing other challenges with the automatism (i.e. automatic detection of patterns that are turned into dice-roller formulas) since some patterns include english words ('to hit' for example) but this is for another day. Anyway, long story short, I thought about creating the dice-roller formulas myself, instead of counting on the statblocks plugin to do it for me.

It then became possible to have a Block rendered as Markdown (i.e. so that you can link Spells to specific notes for example) with dice-rollers: cool :-)
But then... I realized that the 5e-statblocks plugin was adding its own layer on top of dice-roller by managing an initial dice result equal to the average.
(i.e. in our books, we have: ... 10 (2d6 + 3) slashing damage. 10 is (2d6+3) average value and this is handled by 5e-statblocks plugin nicely).

But once "manually" adding dice-rollers in Markdown rendered blocks, you loose this specific processing provided by 5e-statblocks and so... no average value anymore.

But, wait, why not add this ability natively in the dice-roller plugin? 

This was the feature request... but while thinking about this... I developed it along the way ;-)

And here's how:
I added this ability directly in the dice-roller plugin using a new flag: `|avg`.

Adding `dice: 2d6 + 3|avg` in a note will display: `10 []`  and the tooltip will contain: `average: [3.5,3.5]+3` (the [] represents the dice symbol in case you wouldn't have recognized it!).

While developping this, I noticed the issue #98 asking for an empty initial value.
So, I added another flag: `|none` allowing to display an empty result when first rendering a dice-roller.

I also thought about another interesting case where I don't want the dice value to be rendered in my note directly, having it in the tooltip being enough. This about Skills for example. 
Instead of displaying `Stealth +6 **(10)**` I'd be happy just displaying `Stealth +6` and having the value only when hovering on it (i.e. in the tooltip). When you have monsters with lots of skills, this is really messy when each one displays a random roll besides it.

So, one more flag to the rescue: `text(...)`
Example: `dice: 1d20 + 6|nodice|text(Stealth +6)` and you have it. Display is `Stealth +6`, tooltip shows the rolled value, and you can, of course, still click on it to reroll.
You can even combine text and avg so that the "default" skill roll be the average: `dice: 1d20 + 6|nodice|avg|text(Stealth +6)`

And... lastly, as I was adding flags, I also made changes so that `|form` and `|noform` can be added to a dice-roller (they were available only for dice-mod).

**Comment by JYCasalis** [comment]
Oh... I forgot... one last thing...

I also made changes so that if you `Alt-click` on a dice formula, it will display the Average and if you `Ctrl-click` it will display an empty result.
Warning: I don't know if this works on Mac (`Cmd-click` and `Ctrl-click` I would guess).

**Comment by valentine195** [comment]
Closed by PR #105
