### ISSUE TITLE
Allow Dice-Mod to tag precidence over sub rolls.

### ISSUE THREAD

**Issue by HAJ523** [valentine195/obsidian-dice-roller#114]
When rolling using `dice-mod:` it would be helpful if the sub rolls AKA tables roll into tables into tables. Would all apply as if they were in dice-mod mode all the way down. 

This would allow for the creation of multi roll tables where our tables would not be ruined by clicking preview mode.

Example:
Table 1 has 3 options and all of those options roll on table 2,3,4 respectively.
Calling `dice-mod: [[^table1]]` should result in the table 2,3,4 rolls returning inline.

![Recording 2022-05-24 at 21 29 38](https://user-images.githubusercontent.com/552256/170166904-1ee6598a-34b3-45f5-a078-60a2f7c301d1.gif)

**Comment by JYCasalis** [comment]
@HAJ523 
Should work as you were expecting with 8.5.0.

**Comment by HAJ523** [comment]
This was fixed also!
