### ISSUE TITLE
TableRoller - "redesigned"

### ISSUE THREAD

**Issue by JYCasalis** [valentine195/obsidian-dice-roller#116]
Hi all,

I spent some time updating the TableRoller and am now ready to share the result with you!

First things first, you can find what I'd call a beta here: https://github.com/JYCasalis/obsidian-dice-roller/tree/beta-table-roller
(you can pull this branch, build the plugin and test it if you want).

With the existing design, sub rollers are managed by relying on markdown rendering. Sub rollers are rendered "recursively" (that's why, at the end of the day, you may have multiple dice icons since, in fact, you have multiple rollers render in your note.

The new design, on the contrary, trigger the sub roller computations but does not render them as such. 
So, at the end of the day, you have one single roller in your note showing a result that has been built by "recursively" computing results from sub rollers.

Maybe clearer with some images.
Existing design: three rollers (green is the Table roller, red and blue are the dice-rollers obtained by rendering the table roller result)
![image](https://user-images.githubusercontent.com/9211839/170264501-3af3b79a-4cf1-449a-9b1a-ded732c58f41.png)

New design: one single table roller (values of the dice-rollers have been rolled and retrieved but the corresponding rollers are not rendered).
![image](https://user-images.githubusercontent.com/9211839/170264915-deff9715-aa68-4dfe-8b83-f0ab089e0b79.png)

More to come...

**Comment by JYCasalis** [comment]
Please note that I had issues with tooltip styling.
I wanted the width not to be limited to 300px (I guess this is the default in obsidian) 
And, as I chose to use indents, I wanted to get rid of the centering applied by default in tooltips.

I had not been able to find a proper way to customize only tooltips related to dice-roller, so... I just added the following snippet (which applies to all obsidian tooltips):

`
.tooltip {
    max-width: unset !important;
	text-align: left;
}
`

**Comment by JYCasalis** [comment]
Last example based on issue #114:

![image](https://user-images.githubusercontent.com/9211839/170269351-c507e949-edad-4cb9-9561-1368e4c59b80.png)

**Comment by JYCasalis** [comment]
So...

Jeremy, do you see anything of interest to you in this redesign?

If yes, then I think it would be helpful to discuss a few technical details together. 
Maybe I should create a PR NOT to be merged, but that you can review & comment (and I could add my own comments in the review too) ?

Not sure what's the easiest, let me know!

**Comment by valentine195** [comment]
Yeah, this looks awesome and pretty much what I would want to do anyway. Are you open to making a PR so I can review the diffs?

**Comment by valentine195** [comment]
Also - thanks so much for putting all this time into dice roller. I recently got a new job and haven’t had much coding time at all since then!

**Comment by HAJ523** [comment]
This appears to solve issues #114 & #115 based on my limited testing.

**Comment by JYCasalis** [comment]
> Yeah, this looks awesome and pretty much what I would want to do anyway. Are you open to making a PR so I can review the diffs?

Just pushed a PR with my changes.

As I said, there are still "details" that can be discussed / improved / refined / whatever 😉 

The PR does not include the css changes I mentioned above for .tooltip) as I don't know if that is good practice to change such a global css target from a plugin (and maybe there's a better way?).

On the other hand, it contains two other css changes that I made so that dice-mod results look better (no more automatic bold applied to dice-roller results, and more accurate rendering when rendering several table-rollers in the same paragraph).

**Comment by JYCasalis** [comment]
> Also - thanks so much for putting all this time into dice roller. I recently got a new job and haven’t had much coding time at all since then!

Grats for your new job!

I had some free time on my side (I was on vacation 😜), and that has been (and still is) a lot of fun to discover, learn and play with obsidian, plugins, typescript, github, ...

**Comment by JYCasalis** [comment]
> This appears to solve issues #114 & #115 based on my limited testing.

Thanks!

Do not hesitate to report here if you find any unexpected behavior (in case you'd keep the beta running of course).

**Comment by HAJ523** [comment]
Just a note after further testing this doesn't completely fix #115 it does reduce the occurrence however. 

You can re-create it by just using `dice-mod: 1d6` repeated in your file a couple of times and clicking the preview.

**Comment by JYCasalis** [comment]
@HAJ523 
If you can check again with the latest version (8.5.0), it should work now (hopefully).

**Comment by HAJ523** [comment]
I was testing yesterday! It works perfectly.

**Comment by JYCasalis** [comment]
Thanks for your feedback @HAJ523 😍

Closing my own issue then!
