### ISSUE TITLE
Feature request: Show result source inline

### ISSUE THREAD

**Issue by davidolrik** [valentine195/obsidian-dice-roller#12]
It would be nice to be able to see the source of the result inline, instead of having to hover over the result.

**Comment by valentine195** [comment]
For which type of roller? All of them?

**Comment by davidolrik** [comment]
Yes, I like what is in the tool tip, I would just rather be able to see the whole "equation" without having to hover. 

This would also be an improvement on mobile where the tooltip doesn't work. 

Something like this: `2d6-1 => 4+2-1 = 5`
