### ISSUE TITLE
Conjoined inline-blocks don't roll properly.

### ISSUE THREAD

**Issue by HAJ523** [valentine195/obsidian-dice-roller#120]
When using 2 rolls where you want the results to be placed right next to one another the interpreter doesn't properly roll both cases:

Example (`` replaced wtih '):
`'dice-mod: [[Syllable-Name^Syl1]]''dice-mod: [[Syllable-Name^Syl2]]'`

According to the roll formla in the text it appears as if it is trying to do the following roll:
`dice-mod: [[Syllable-Name^Syl1]]''dice-mod: [[Syllable-Name^Syl2]]`

When it should treat each of them seperately.

(I apologize for testing the limits of what the roller is capable of.)

**Comment by valentine195** [comment]
Obsidian considers inline code blocks next to each other like that as one single code block, which is what causes this. You need a space between them.
