### ISSUE TITLE
Open link in existing pane

### ISSUE THREAD

**Issue by kmaustral** [valentine195/obsidian-dice-roller#121]
I'm glad to have found the link function for Dice Roller, which is a great substitute for the Random Note function. 

Currently, it will always open a new pane when clicked. Would it be possible to have an option for it to open in the same pane? It would safe having to keep closing panes. 

Thank you!

**Comment by valentine195** [comment]
As of 8.5.1, Links will now open in the same pane by default.  Control-click a link to open in a new pane.

**Comment by kmaustral** [comment]
Thanks. It works wonderfully now.
