### ISSUE TITLE
Dice rolling in live preview mode

### ISSUE THREAD

**Issue by Gourav1910** [valentine195/obsidian-dice-roller#123]
Is it possible to dice roll in live preview mode? In my writing process I made a setup in which I dice roll to get promoted text from a table but I can't able to see that text in my editing (live preview) mode. If that possible, it will be very helpful.

**Comment by valentine195** [comment]
Sorry, it is not. Live preview support for something like dice roller is very technically complex and unlikely for something like the section roller or tag roller. I do plan on doing this, eventually, but it might take awhile.

**Comment by Gourav1910** [comment]
Ok no problem. Thanks.

**Comment by valentine195** [comment]
This was implemented in the latest release

**Comment by williampayne23** [comment]
I'm trying to use this in live preview at the moment and it's not rendering, is there a specific flag for this (I don't see anything in the documentation to indicate that)
