### ISSUE TITLE
Request - Not rendering dice on opening a file

### ISSUE THREAD

**Issue by zifre** [valentine195/obsidian-dice-roller#127]
Hi, this is a great plugin and thank you for creating it!

**Request**
If the option "_Always Render Dice_" is enabled and you open a file. The plugin will render all the dice rolls one by one and this can take a while if your file has several dice rolls. 

I would like to request an option to NOT render dice when opening files but rendering them at all other times. Is this feasible?

Thanks!

**Comment by Hyfro-Cyrup** [comment]
I second this. I tried using the "|avg" tag so that it would take the average value first instead of rendering. However, I am either misunderstanding how |avg is supposed to be used or it isn't working properly.

**Comment by valentine195** [comment]
this was fixed, sorry for not closing
