### ISSUE TITLE
Is this plugin working on Android?

### ISSUE THREAD

**Issue by JuergenKaettnis** [valentine195/obsidian-dice-roller#128]
I  installed the plugin without changing any setting. Then I created a new file and tried several of the syntaxes from the help file for the plugin. In any case, the code blocks were not rendered. I give you one of my example code blocks:

  ˋdice: #Testschlagwort|Link` 

I hoped that it would deliver a random file with the tag #Testschlagwort.

I am using Samsung S4 Tablet with all Software up to date. 

Am I doing something wrong?
Is the plugin not working on mobile devices?
What else could be my issue?

Thanks for the help in advance.
Best greetings.

**Comment by valentine195** [comment]
Do you have Dataview installed? Tag rolling requires Dataview. 

If so, do any other rollers work?

**Comment by Hansilein00726** [comment]
Hello again,
as Lionel Richie says.😉

I have dataview installed. I am very much in the beginning stage of experimenting with the plugin. Therefore until now, I was unable to get any dicer rolling. My last result is the following
![SmartSelect_20220620-140400_Obsidian](https://user-images.githubusercontent.com/95701413/174597792-dad01826-da01-4b89-9d6b-331f9d461ee5.jpg)
That's not what I expected. The blue at the left side are file names, but I am even not sure, if they really have this tag.

My syntax for this result was:

  ```
  dice:#Testschlagwort|Link
```

I didn't change anything in the settings. I should have the standard settings.

I have a lot of plugins installed. Shortly broke the 50 plugins border. Anything else is working.

I am especially interested in the functionality to randomly select an line or block from a file that still matches certain conditions like tags etc.

Thanks for the quick respond, anyway.

**Comment by Hansilein00726** [comment]
Probably, it is more or less working now. And probably, I mean just probably, I had some misunderstandings. Maybe we can close this issue now?
