### ISSUE TITLE
Copy button only copies one line of output

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [valentine195/obsidian-dice-roller#13]
I have a note containing separated lines and am using `dice: 3d[[What to do today]]` which correctly displays a random selection of 3 lines. Hitting the copy button only copies the first of the three lines.

I can't select the text manually either, once you let go of the mouse button the list refreshes

**Comment by valentine195** [comment]
This was actually a bug with the copy button placement. There should be one button per block. Do you need a button to copy all of them?
