### ISSUE TITLE
(Hopefully small) Feature Request: Display formula result with graphical dice

### ISSUE THREAD

**Issue by Hyfro-Cyrup** [valentine195/obsidian-dice-roller#130]
First of all thank you so much. Your plugins have completely transformed my notetaking. 

I love the ability to render dice rolls as well, but it seems to be more trouble than its worth in most instances because it only shows the raw dice values and not the result. If you roll multiple dice or modify the result in any way--especially if you're trying to reduce clutter with |text--it seems a little pointless to see the dice and then still have to check somewhere else or re-hover to see what the result is. 

This could be fixed with a little popup text like a video game damage indicator that shows the result next to the rendered dice, or even just showing it in the toolbar if that would be easier.

**Comment by Cammagno** [comment]
I support this request, it will be nice :)
