### ISSUE TITLE
Enhancement: Toggle to put the dice icon/button on the left

### ISSUE THREAD

**Issue by cyberfunkr** [valentine195/obsidian-dice-roller#136]
This is purely a cosmetic change.

I would like a toggle to put the icon/button of dice on the left and the results be on the right.

The reason is simple; with anything except for a single digit result, the button moves with every roll. With a d12 or d20, it's not that drastic, just a little annoying. But when printing the results of tables, it can jump anywhere--wherever the line happens to end. This means I'm searching for the button if/when I need to re-roll.

It would be much easier if the button was always in the same spot, and the text wrapped around as needed.

**Comment by valentine195** [comment]
You might be able to do this with css. Try a snippet with:

```css
.dice-roller {
    flex-flow: row-reverse;
}
```

**Comment by cyberfunkr** [comment]
Yup that works like a charm. Thank you. But you still may want to have it as an option; either a toggle in the settings screen or somewhere in the documentation.

**Comment by Cammagno** [comment]
> Try a snippet with:
This works nice, thanks

With also something like this, to space the die from the formula a bit:
}
.dice-roller-button {
    padding-right: 5px;
}
