### ISSUE TITLE
FR: option to always render dice, but not at sturtup

### ISSUE THREAD

**Issue by Cammagno** [valentine195/obsidian-dice-roller#138]
I'd like an option (and maybe also a render flag to locally overwrite it) to always render dice, but not at startup (when the note is opend), only when the dice are manually rolled.

**Comment by Cammagno** [comment]
This will be useful in particular for notes with multiple dice formulas in them: as it is now, each time I open them a lot of dice keep being thrown over them

**Comment by Zagor91** [comment]
`dice: 1d6|none` : Displays no value before clicking the icon.
`dice: 1d6|render` : Rolls 3D dice when opening the page.
But
`dice: 1d6|none|render` : Also rolls 3D dice when opening the page and ignores the option none.

**Comment by Cammagno** [comment]
> `dice: 1d6|none|render` : Also rolls 3D dice when opening the page and ignores the option none.

also dice: 2d6|none rolls 3D dice when opening the page ignoring the option none if the option Always Render Dice is on.

AFAIK there is no way to avoid the 3D roll when opening the page, if not to disable 3D roll at all.

**Comment by valentine195** [comment]
This is a good idea, I’ll implement this when I get a chance.
