### ISSUE TITLE
Bug: Exploding dice on Dice Condition

### ISSUE THREAD

**Issue by Yilmas** [valentine195/obsidian-dice-roller#146]
I think there might be an issue with dice conditions when combined with exploding die, see image below.

> ![image](https://user-images.githubusercontent.com/6323003/193118027-8a6b0958-d46c-46a2-943f-6ebaacae7480.png)

Although, it might just be a syntax issue on my part. However, the table:

> ![image](https://user-images.githubusercontent.com/6323003/193117836-37cdd80e-84bf-4ec7-ac22-54102c22b23e.png)

Only mentions an issue when using: `=!{n}`*, which I'm not using here.

It seems to be exploding on dice condition true, and not on max value - which I would have expected.

**Comment by valentine195** [comment]
This is being interpreted as a [Modifier Condition](https://github.com/valentine195/obsidian-dice-roller#modifier-conditions)
