### ISSUE TITLE
[feature requst] post the result into a other file and read values from there

### ISSUE THREAD

**Issue by Parlazo** [valentine195/obsidian-dice-roller#15]
[feature requst] post the result into a other file and read values from there

stats file.md
value1 = 6
value2= 3

content.md
your value1 is 6 ... press dice
your value2 is 3 ... press dice

(reload page or other page)

content2.md
now your value1 is 2
and your value2 is 4

the idea is to use the stats file as a player profile where he can have items with value
and then write a story where he can see the item(s) and the value and where he can dice a new value to his stats file
and so load a new link or transclude a new story part

so in that way he gets a playable dynamic story saved in his stats file

some how
i hope you get the picture i dont know if it is possible but it would be awesome

thanks any way

**Comment by valentine195** [comment]
I'm sorry, I don't think this would be possible with the plugin as written. You could always put the dice on its own line in a third file, then embed the block into `stats` and `content`.


Example:

## dice.md

`dice: 1d6`
^block-ref

## stats.md

value1: ![[dice^block-ref]]

## content.md

your value1 is ![[dice^block-ref]]
