### ISSUE TITLE
JS plugin.getRoller() not rendering dice graphics

### ISSUE THREAD

**Issue by jon-heard** [valentine195/obsidian-dice-roller#150]
Hi.  Recently I noticed that the plugin's Javascript function `getRoller()`, followed by `roll()` is not showing dice graphics.  Previously, it would render dice when the setting "Always render dice" was turned on.

I tried adding "|render" to the end of the input strings, like `d100|render`, but I still don't see the dice roll graphics.  I _do_ see them when I add `|render` to the links in the note.

Is there anything else I need to do to show graphics with `getRoller()`?

Thanks for your help.  And thanks for this neat plugin!

**Comment by valentine195** [comment]
Hey, I fixed this, but you'll have to set another flag to get it to roll immediately OR roll with a parameter.

```js
const dice = plugin.getRoller();
dice.hasRunOnce = true;
dice.roll();
```

OR

```js
const dice = plugin.getRoller();
dice.roll(true);
```
