### ISSUE TITLE
Weird rendering artifact when extracting a random line from another file

### ISSUE THREAD

**Issue by carlsverre** [valentine195/obsidian-dice-roller#160]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/82591/214798544-72502474-bab2-474b-ad5b-7a5adbf3afc2.png">

File contains list of names, one per line:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/82591/214798602-f432f5af-96b5-4e46-901e-648bd3c50754.png">

Formula is `dice: [[first name]]|line`

Not sure why the additional purple lines are showing up beside the output, perhaps it's something with my config but I can't seem to figure it out. Any pointers would be very helpful!

```
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Dataview v0.5.55
		2: Dice Roller v8.8.2
		3: Outliner v4.2.1
		4: Templater v1.16.0
		5: Advanced Tables v0.18.1
		6: Excalidraw v1.8.11
		7: Natural Language Dates v0.6.1
```

**Comment by valentine195** [comment]
The `line` roller creates a series of embeds (like `![[names.md]]`, which has that line.
