### ISSUE TITLE
Control over styling / ability to disable styling

### ISSUE THREAD

**Issue by aschearer** [valentine195/obsidian-dice-roller#161]
![image](https://user-images.githubusercontent.com/24077/215937075-795fa6af-787a-42c1-92a1-e27b8f439289.png)

See attached. Above maps to:

```
>[!QUOTE]
>Take things as they are. Punch when you have to punch. Kick when you have to kick.
>— Bruce Lee

>[!QUOTE]
`dice: [[daily note quotes]]|blockquote`
```

Copying the results of the dice quote and overwriting the dice line yields a line like the above quote, rendering correctly.

This is on Obsidian 1.1.9 using the Default theme.

**Comment by merylstreet** [comment]
Looking for a similar option.
I am trying to fiddle with the css code to make below block more compact; having this control within the plugin would be super helpful.

![image](https://user-images.githubusercontent.com/4256618/217212654-6c60e5d2-8f1d-441b-9116-e375d460127f.png)
