### ISSUE TITLE
Exploding dice - graphical dice "explode" too much following single cap roll

### ISSUE THREAD

**Issue by jot-chipset** [valentine195/obsidian-dice-roller#164]
Tested on Mac and iOS. This only occurs when I use |reveal or if I enable graphical dice on all rolls. Tested with d4, d6, and d8. A single maximum roll on these rerolls multiple times (not sure about the pattern) even if the subsequent rolls do not hit the maximum. I do not think it occurs without the graphical display because I've never seen the results be as absurdly high as they are with the graphical display.
<img width="535" alt="Screenshot 2023-02-24 at 4 16 21 PM" src="https://user-images.githubusercontent.com/125768607/221230743-c2d28dea-053f-4716-a07f-4cbec1158103.png">
![IMG_0164](https://user-images.githubusercontent.com/125768607/221230819-a2888856-ba0f-4c44-b958-a690babe66d3.jpeg)

**Comment by jot-chipset** [comment]
Should also mention that this is occurring on the latest version of dice-roller available through the check-updates menu on both systems.

**Comment by gitDalex** [comment]
I have the same problem with a simple ``dice 1d6!{1}``: the dice roller throw one more dice every time for example [6!,1,3] = 10  !! the result should be 7 not 10 !
my personal best is 1d6!{1} = 154 !! (wtf? for a result theoretically  in between 1 and 12 ;)
