### ISSUE TITLE
Feature Request: World/Chronicles of Darkness dice

### ISSUE THREAD

**Issue by JepheDelPhuego** [valentine195/obsidian-dice-roller#21]
In World of Darkness you roll d10s, and it has a target number. For every die that hits the target number or above, you get a success. 1s can subtract successes and 10s (or sometimes 9s or 8s) can grant an additional die to roll. These modifiers would be great features for the dice roller! :)

**Comment by valentine195** [comment]
Hi, the ability to do this was added in 6.0.0.

`dice: 1d10=10-=1` will return `1` for dice equal to 10, `-1` for dice equal to 1, and `0` for all others. See [here](https://github.com/valentine195/obsidian-dice-roller#dice-conditions).
