### ISSUE TITLE
-1 modifier breaks click to re-roll

### ISSUE THREAD

**Issue by davidolrik** [valentine195/obsidian-dice-roller#26]
This formula `dice: 2d6-1` only gets calculated once and it's always calculated as `-1`, and clicking on it doesn't re-roll.

E.g. `dice: 2d6-1` gives me `2d6 -1 -> [4, 3] -1 -> -1`

Formula without the `-1` works.

Tested on 6.0.1

**Comment by valentine195** [comment]
If you put a space between the characters (2d6 - 1) it will work. A fix for no spaces should be out soon!
