### ISSUE TITLE
Allow dice numbers to be omitted

### ISSUE THREAD

**Issue by Obsidian1212** [valentine195/obsidian-dice-roller#27]
A lot of times when I and my friends play COC we usually just omit the number when only roll dices once (and our software supports that too)
For example:
`1d100` would just be `d100` and
`d100+d10` would be equivalent to `1d100+1d10`.

Another less used thing is that, sometimes we also omit the dice faces if it is an 100 faces die.
For example:
`2d` is equal to `2d100` and
in extreme (yet really common) cases
when we just type in `d` it works as `1d100`.

That is currently not possible here. Um, may I ask support for that?
(Or even better, let us customize the default values?)

**Comment by valentine195** [comment]
Hi, I added both the ability to omit the rolls and faces and the ability to customize their defaults in settings (although I just made them default to 1 and 100 respectively).

**Comment by Obsidian1212** [comment]
Thank you so much!
