### ISSUE TITLE
[Feature Request] Replace the whole `dice: ` block with its result as plain text

### ISSUE THREAD

**Issue by Obsidian1212** [valentine195/obsidian-dice-roller#31]
I'm thinking of a concept like this.

Maybe a block like `dice-text: ` that directly saves the result that replaces the block itself with plain text of the results.

I'll use `1d100` as example:

User inputs `dice-text: 1d100`.
When going back to preview, this could shown as something like this:

`[1d100 - Click to roll!]`

And when clicked, let's say I got a 58, then it becomes:

`1d100 → [58] → 58`

And this exact text is saved inside the markdown file, overwriting the `dice-text` block. (Going back to the editing mode shows the same result text too)

I'm thinking like this could be really useful if dice rolls need to be recorded. (COCTRPG gamr recordings, etc.) 
Although this won't prevent the user manually modifying the dice, this way however completely eliminated the probability of losing the original dice result, and allowed results to be safely saved.

Also, thank you for this wonderful plugin!

**Comment by valentine195** [comment]
I could implement this, but just to be clear, it won't ever be a dice roller again once it is replaced in the note text.

**Comment by Obsidian1212** [comment]
I mean, that's my exact point, like this could also avoid people accidentally re-clicking on dices they wanted to save.

I know this is very different than a normal dice roller, so I suggested another block name (`dice-text`, or anything else that sounded great)

I don't know how this idea sounded to you tho.
It's up to you to choose to deny or accept my request.

**Comment by Obsidian1212** [comment]
oh my

THANK. YOU. SO. MUCH.

**Comment by Obsidian1212** [comment]
Um it said failed to install the plugin.
