### ISSUE TITLE
The order of plugins get loaded can cause different behaviors of the plugins

### ISSUE THREAD

**Issue by Obsidian1212** [valentine195/obsidian-dice-roller#33]
![Screenshot_20210926-172904535](https://user-images.githubusercontent.com/35908303/134801984-b1044427-4bb1-4b30-a947-1e5079a1ad08.jpg)

Not really asking for a fix, but I think this is...pretty interesting.

Wonder why it happens tho.

**Comment by valentine195** [comment]
Interesting. It must effect the order of the post processors, but the admonitions plugin should be re-rendering everything inside anyway… I’ll try to investigate but no promises unfortunately.

**Comment by heliostatic** [comment]
Ah, I just encountered this today as well with Admonition.

**Comment by valentine195** [comment]
I can't figure this one out! Not sure what causes this at all.
