### ISSUE TITLE
Can't get individual list items with block dice

### ISSUE THREAD

**Issue by mure** [valentine195/obsidian-dice-roller#34]
Using block dice, I'm able to get the full contents of a list, but not individual list items. I also tried using
`dice: [[note]]|listItem`, but no dice (hah).

![Screen Shot 2021-09-27 at 4 33 07 PM](https://user-images.githubusercontent.com/9257800/134988454-9ec2a0d5-bd37-402e-b1e5-287be0b7798c.png)
![Screen Shot 2021-09-27 at 4 33 23 PM](https://user-images.githubusercontent.com/9257800/134988496-7864c59c-a119-4a44-af15-6efc877de541.png)

**Comment by valentine195** [comment]
Someone else mentioned this, so I’m not sure it’s actually possible unfortunately. 

Once I’m back at my computer I’ll look and see if these are exposed

**Comment by mure** [comment]
I think it should be possible - there's a separate cache for list items:
https://github.com/obsidianmd/obsidian-api/blob/5af3ef982328a2dd0a2f5242f3c74e2f45e07896/obsidian.d.ts#L378

**Comment by mure** [comment]
Maybe something like:
```javascript
async getOptions() {
        this.cache = this.plugin.app.metadataCache.getFileCache(this.file);
        console.log(this.cache);
        if (!this.cache || !this.cache.sections) {
            throw new Error("Could not read file cache.");
        }
        this.content = await this.plugin.app.vault.cachedRead(this.file);
        this.options = this.cache.sections.filter(({ type }) =>
            this.types
                ? this.types.includes(type)
                : !["yaml", "thematicBreak"].includes(type)
        );
        // ** Add this **
        if (this.types.includes("listItem")) {
            this.options.push(...this.cache.listItems);
        }
        this.loaded = true;
        this.trigger("loaded");
    }
```
In the SectionRoller class. And you'll have to fix up the types to accept both SectionCache and ListItemCache

**Comment by valentine195** [comment]
Aha, good find. I’ll probably end up making a new class for this (ListItemRoller) and allow the ability to specify a block id like for Table Rolling as well.

**Comment by valentine195** [comment]
Thanks for the protip, this has been added in 6.5.1.
