### ISSUE TITLE
6.5.1 is broken 😅

### ISSUE THREAD

**Issue by mure** [valentine195/obsidian-dice-roller#36]
Hi, it's me again. 6.5.1 is crashing:

<img width="688" alt="Screen Shot 2021-09-28 at 3 14 17 PM" src="https://user-images.githubusercontent.com/9257800/135159040-bd973a27-7c0b-4773-92ca-e2b276d20559.png">
<img width="576" alt="Screen Shot 2021-09-28 at 3 14 31 PM" src="https://user-images.githubusercontent.com/9257800/135159075-93775355-ca6e-448f-a606-35e8025ecd95.png">

It appears my suggestions have caused problems :P

**Comment by valentine195** [comment]
My guess is it’ll work if you add a type. Will fix ASAP

**Comment by mure** [comment]
Ah I see. Just need a null check or init the types to an empty array.

**Comment by valentine195** [comment]
Should work now, sorry about that!
