### ISSUE TITLE
render dice rolls in edit mode

### ISSUE THREAD

**Issue by cristianmtr** [valentine195/obsidian-dice-roller#44]
Hey. Would it be possible to render the dice rolls directly in edit mode, without having to switch to preview mode and back again? I am using the 

```
`dice-mod: 3d100 + 12`
```

syntax

**Comment by valentine195** [comment]
Hi, sorry, I do not think this is feasible at this time. Once the new Live Preview feature is able to support markdown processors I will add this.

**Comment by hekimolacagim** [comment]
Any update on this planned feature?
![image](https://user-images.githubusercontent.com/104320938/170114034-ed6f5ba2-2364-4f1c-bdbe-937ea99b0ee7.png)
