### ISSUE TITLE
[Feature Request] Toggle to Hide Dice Roll Pane

### ISSUE THREAD

**Issue by SlRvb** [valentine195/obsidian-dice-roller#45]
While I do like having the dice pane auto open in my D&D vault, it's a little less useful in my Story vault and keeps covering my graph views.

A toggle to prevent the dice roller pane from opening every time on startup would be nice.

![Obsidian_LYKmnJOSnz](https://user-images.githubusercontent.com/54087190/137545168-7c971953-6f71-4b98-9b4f-5667fddf8461.png)

**Comment by valentine195** [comment]
Whoops I actually left this in for development accidentally. It shouldn’t autofocus (although I can add a toggle). Will remove asap!

**Comment by valentine195** [comment]
Closed in 7.1.4
