### ISSUE TITLE
dice rolls with dataview variables?

### ISSUE THREAD

**Issue by cristianmtr** [valentine195/obsidian-dice-roller#48]
Could it be possible to add dataview numbers to the dice formulas?

Example.

I declare a value using the DataView syntax in the file.

```
some_nr:: 10
```

and then I use it in various dice formulas in the page

```
`dice: 2d6 + some_nr`

`dice: d20 - some_nr`
```

etc.

If this is implementable, I could also have a look and submit a PR

**Comment by heliostatic** [comment]
I would also be interested in this for handling skill rolls that add an attribute modifier (as in D&D or other TTRPGs).

**Comment by valentine195** [comment]
Just pushed 7.8.0 which adds basic support for Dataview. See [here](https://github.com/valentine195/obsidian-dice-roller#dataview-integration),

**Comment by lolbat** [comment]
Is it possible to add support for fields defined in different notes? 

`dice: 1d6 + [[_Stats]].Edge`

for example?
