### ISSUE TITLE
Rolling tables sometimes shows incorrect rows, links with trailing spaces don't work correctly

### ISSUE THREAD

**Issue by Pachtjuilaard** [valentine195/obsidian-dice-roller#49]
Hi,

I found two issues with rolling on tables. I have 7 tables on one page, the first table having 6 rows with inline dice rolls that roll for the 6 other tables. These inline rolls sometimes give the table separator row ( |---|---| ) as a result, sometimes the header row and sometimes even part of the block name link header thing (it shows"^very-" when the text on that line is "^very-common-plants". This can't consistently be reproduced however, it just sometimes... happens a few times.

Secondly, those 6 tables all have links to other pages in them. The result of the roll displays the link, but if there's spaces behind the linked text ("[[Other Note    ]]"), the link in the roll result doesn't refer to the correct page and makes a new note. The original link being referred to, the one in the table, works fine however.

**Comment by Pachtjuilaard** [comment]
The links in the roll results work fine when all trailing spaces are deleted. So for now, it's a pragmatig workaround to just find all cases of " ]]", replace them with "]]" and just spam click the Replace All button until all trailing spaces are gone.

**Comment by WychWitch** [comment]
I've always encountered this when the dice table's dice isn't accurate to the numbers, sometimes when I add a row and forgot to update the dice for example. Maybe that's it??

**Comment by Pachtjuilaard** [comment]
All seems to be working rather fine now! My first issue still only appears when constantly editing tables, which also then resolves itself after switching between edit and reading mode.

Haven't seen the second issue again too!
