### ISSUE TITLE
Persistent results

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-dice-roller#5]

**Comment by umiaki** [comment]
Yes please

**Comment by valentine195** [comment]
> Yes please

Hi, this has been added in 6.1.0. Please see [Saving Results in the Readme](https://github.com/valentine195/obsidian-dice-roller#saving-results).

**Comment by umiaki** [comment]
Does not seem to work :/
Tried both with global settings and dice+:

**Comment by valentine195** [comment]
Can you give me more information? Did you update the plugin?

Are there any errors in the developer console (Ctrl/Shift/i or Cmd/Alt/i)?

This works for me... 🤔

**Comment by umiaki** [comment]
Yes, both obsidian and plugin are up to date.

main.ts:173 Uncaught (in promise) TypeError: Cannot set property '28' of undefined
    at DiceRollerPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:2805:52)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:28:58)

**Comment by valentine195** [comment]
Can you try 6.2.1?

**Comment by umiaki** [comment]
Well I don't get the error in console now, but it still does not work. Neither global settings or +:/

**Comment by valentine195** [comment]
Hmm, really bizarre. I can't get replicate this. Can you try closing and re-opening Obsidian, and if that doesn't work, uninstalling and re-installing the plugin?
![dice](https://user-images.githubusercontent.com/38669521/133831909-ddb610e1-8a0f-47e6-bdb2-49cdb9068973.gif)

**Comment by umiaki** [comment]
Yeah, forgot to mention that. I've already done both of those things.
Deleted my stored formulas but still does not work.
Testing on simple `dice: 3d4 + 3` and `dice+: 3d4 + 3`  - switching to another note and back rerolls the dice.
You said there is a chance this does not work for you. I would pursue why this does not work, it might not work for other people more often.
I hope I'm using the plugin right, friday evening, maybe I've missed some simple step?

**Comment by valentine195** [comment]
Ah, I think I may know why. Do they save if you _close the note and re-open it?_

**Comment by umiaki** [comment]
Yes :)
Sometimes they change but that is when some popup shows preview of other page, which I guess is the same as swithing the note.

**Comment by umiaki** [comment]
Btw I'm not sure how the plugins work, but can't you just store the result in the note itself?
Like 'dice: 3d6 + 10', roll -> 'dice: 3d6 + 10 = 15'?
This would be useful, because then I can just share the note with someone who would have the same result.
This approach would then be useful in statblock as well.

**Comment by valentine195** [comment]
That could work for dice, but not the tag, table or block rollers. I’m also not sure I would want the plugin to modify files. 

I have a fix coming soon for the issue you’re running into, though.

**Comment by umiaki** [comment]
Right.
Great, many thanks!

**Comment by valentine195** [comment]
Okay, I *think* 6.3.0 will fix these issues. Please try it out and let me know.

**Comment by umiaki** [comment]
Yeah, works fine with closing the note or swithing to another and back or going to edit mode and back.
However, dice change if you go to edit mode and change something within the paragraph, like:
"Test paragraph rolling `dice+: 3d4 + 3`" -> "Test this paragraph rolling `dice+: 3d4 + 3`"
It also changes sometimes if you quickly go to anoter note, close it and open the one with dice. This is kinda random and I'm not sure why it happens.

**Comment by valentine195** [comment]
Thank you! I will try to investigate. The way this feature works isn't super robust - it's hard to find the context of _which roller_ each result is tied to, especially if changes are made quickly, unfortunately.
