### ISSUE TITLE
Multiple look-up tables in one table element renders that row unable to be rolled, and strange display error when trying to recreate

### ISSUE THREAD

**Issue by WychWitch** [valentine195/obsidian-dice-roller#50]
Hello! I've been experimenting with this plugin and it's been amazing! However I've run into an issue where if I have multiple look up tables within the same element, the roller will instead refuse to roll that, rolling any other values instead.

I tried to recreate it using a minimum test case, but I'm encountering a weird error?? where it outright refuses to display the lookup table and instead displaying the raw text.

If it matters I am also using the Advanced Tables plugin, but even when disabling it it doesn't seem to work.

Here's the original page I was using, and the issue being repeatable here:

<details>

<summary> Race Generator.md</summary>

```
| dice:1d% |              Races              |
|:--------:|:-------------------------------:|
|   1-63   |  `dice: [[Race Generator#^common]]`  |
|  64-88   | `dice: [[Race Generator#^uncommon]]` |
|  88-100  |   `dice:[[Race Generator#^rare]]`    |
^main

| dice:1d7 |                                 Common Races                                 |
|:--------:|:----------------------------------------------------------------------------:|
|    1     |                                  Plainsfolk                                  |
|    2     |                                  Rabbitfolk                                  |
|    3     |                                   Halfling                                   |
|    4     |                                    Dwarf                                     |
|    5     |                                     Orc                                      |
|    6     |                                     Elf                                      |
|    7     | Half `dice: [[Race Generator#^half-gen]]` and half `dice:[[Race Generator#^main-alt]]` |
^common

| dice:1d6 |            Uncommon Races            |
|:--------:|:------------------------------------:|
|    1     |              Dragonborn              |
|    2     |               Tiefling               |
|    3     |            Minotaur (Yak)            |
|    4     |          Loxodon (Mammoth)           |
|    5     |                Goblin                |
|    6     | `dice: [[Race Generator#^kobold]]` Kobold |
^uncommon

| dice: 1d5 |    Rare Races     |
|:---------:|:-----------------:|
|     1     |      Tabaxi       |
|     2     |      Ijsbeer      |
|     3     | Mousefolk/Ratfolk |
|     4     |       Kenku       |
|     5     |      Tortle       |
^rare

| dice: 1d4 | Very Rare Races |
|:---------:|:---------------:|
|     1     |     Dragon      |
|     2     |     Coeurl      |
|     3     |     Faerie      |
|     4     | Asamir (reroll) |
^very-rare

| dice: 1d% | Kobold Subrace |
| -------- | -------------- |
| 1-50     | Northern       |
| 51-100   | Southern       |
^kobold

| dice: 1d% | Half                              |
| --------- | --------------------------------- |
| 1-70      | Plainsfolk                        |
| 71-100    | `dice: [[Race Generator#^main-alt]]` |
^half-gen

| dice:1d% |                Races No Half                 |
|:--------:|:------------------------------------:|
|   1-63   | `dice: [[Race Generator#^common-alt]]`  |
|  64-88   | `dice: [[Race Generator#^uncommon]]` |
|  88-100  |   `dice:[[Race Generator#^rare]]`    |
^main-alt

| dice:1d6 | Common Races No Half |
|:--------:|:--------------------:|
|    1     |         Elf          |
|    2     |      Rabbitfolk      |
|    3     |       Halfling       |
|    4     |        Dwarf         |
|    5     |         Orc          |
|    6     |      Plainsfolk      |
^common-alt

`dice: [[Race Generator#^main]]`


| dice: 1d4 |                                   Test Table                                    |
|:---------:|:-------------------------------------------------------------------------------:|
|     1     |                                   Plainsfolk                                    |
|     2     | `dice: [[Race Generator#^main-alt]]` and `dice: [[Race Generator#^common-alt]]` |
|     3     | `dice: [[Race Generator#^main-alt]]` and `dice: [[Race Generator#^common-alt]]` |
|     4     |                                      Other                                      |
^test

| dice: 1d4 |                Test2 Table                |
|:---------:|:-----------------------------------------:|
|     1     |                Plainsfolk                 |
|     2     | `dice: [[Race Generator#^kobold]]` Kobold |
|     3     | `dice: [[Race Generator#^kobold]]` Kobold |
|     4     |                   Other                   |
^test2


`dice: [[Race Generator#^test]]]`


`dice: [[Race Generator#^test2]]`

```

</details>

And here's the test file

<details>

<summary> This File.md</summary>

```
| 1d3 | test table 1 |
| --- | ------------ |
| 1   | one          |
| 2   | two          |
| 3   | three        |
^test1

| 1d3 | test table 2 |
| --- | ------------ |
| 1   | one          |
| 2   | two          |
| 3   | three        |
^test2

| 1d3 | test table 3                                                               |
| --- | -------------------------------------------------------------------------- |
| 1   | one                                                                        |
| 2   | `dice: [[This File#^test1]]`                                       |
| 3   | table 1: `dice: [[This File#^test1]]` table 2: `dice: [[This File#^test2]]` |
^test3

`dice: [[This File#^test3]]`
```

</details>

This is what the test file displays when it rolls one of the lookup tables (related to [this issue?](https://github.com/valentine195/obsidian-dice-roller/issues/49)):
![image](https://user-images.githubusercontent.com/1291820/142060615-5cd54f7a-d40d-4856-8f98-368997c33434.png)

I've tried both ITS theme and default.

Maybe my formatting is wrong? It looks correct to me

Thanks in advance!!

**Comment by valentine195** [comment]
So:

1. Yeah, at the moment the lookup table recursion only works if its the _only_ thing in the table. So, `table 1: dice: [[This File#^test1]] table 2: dice: [[This File#^test2]]` won't work.
2. The lookup tables in `This File` aren't correct - the first header needs `dice: 1d3`.

**Comment by WychWitch** [comment]
>     1. Yeah, at the moment the lookup table recursion only works if its the _only_ thing in the table. So, `table 1: dice: [[This File#^test1]] table 2: dice: [[This File#^test2]]` won't work. edit: I guess this isn't strictly true, because things like the kobold table work.

AH YEAH I forgot to mention the Kobold table working, I'm glad you caught that!

> The lookup tables in This File aren't correct - the first header needs dice: 1d3.

ARGH I knew it was something like that!!  Thanks that's been fixed, and it properly reproduces the issue 

> Edit: It specifically seems like having multiple dice rollers in the same lookup table makes it think the second dice roller is the header it should be looking for. Let me see if I can fix this!

Thank you so much!! This will make what this plugin is capable of with nested tables skyrocket ^^

**Comment by valentine195** [comment]
Can you please try 7.2.2?

**Comment by valentine195** [comment]
Also, there is a typo here: `dice: [[Race Generator#^test]]]` (there is an extra `]`)

**Comment by WychWitch** [comment]
> 
> 
> Can you please try 7.2.2?

I just did and it works flawlessly!! Thank you so much!!

> 
> 
> Also, there is a typo here: `dice: [[Race Generator#^test]]]` (there is an extra `]`)
 I WAS WONDERING WHAT WAS WRONG WITH THAT ONE... I didn't mention it not displaying right cos I figured it was something I did (I was right)
 
 I cannot tell you how much these updates have helped me, again, thank you!!
