### ISSUE TITLE
(Hopefully small) Feature Request: command to reroll all dice on page

### ISSUE THREAD

**Issue by WychWitch** [valentine195/obsidian-dice-roller#51]
Hello! I'm back with a small feature request. As I'm building various generators with this plugin, I found that it would be Extremely convenient to have a command to re-roll all the dice on a page instead of clicking each individual dice or clicking off the page and back on. Then it can be combined with the buttons plugin (or even just as a hotkey!)

Thank you so much for all the work you've been doing ;u;

**Comment by valentine195** [comment]
Added in 7.3

**Comment by WychWitch** [comment]
!!! Thank you so much!!! You're always so fast omg
