### ISSUE TITLE
Feature Request: Allow dice tags to be used in dice tables

### ISSUE THREAD

**Issue by WychWitch** [valentine195/obsidian-dice-roller#52]
Hello! I was making some more dice tables and noticed that dice tags don't work if they're placed in dice tables. This is my table for reference!

```md

| dice: 1d4 | Connections                                         |
| --------- | --------------------------------------------------- |
| 1         | They are associated with `dice: #dnd/factions|link` |
| 2         | They're from `dice: #dnd/pc|link`'s past            |
| 3         | They know `dice: #dnd/pc|link`                      |
| 4         | They know `dice: #dnd/npc|link`                     |
```

Many many thanks in advance!!

**Comment by valentine195** [comment]
You have to escape the `|` character. It is being parsed as a table cell.

**Comment by WychWitch** [comment]
> 
> 
> You have to escape the `|` character. It is being parsed as a table cell.

OH DUH that explains it!! 

However when trying that out (escaping with \), it seems to completely ignore the link option, and instead uses the default behavior of grabbing a random block from the tag.

This is my table

```
| dice: 1d4 | Connections                                         |
| --------- | --------------------------------------------------- |
| 1         | They are associated with `dice: #dnd/factions\|link` |
| 2         | They're from `dice: #dnd/pc\|link`'s past            |
| 3         | They know `dice: #dnd/pc\|link`                      |
| 4         | They know `dice: #dnd/npc\|link`                     |
^connections
```
I also tried putting a space between the tag and the `\|link` to no avail.

Am I supposed to use a different escape character? I'm probably making another formatting mistake 😅

**Comment by valentine195** [comment]
Ah, I had the "Return Links" setting on! Whoops :)

**Comment by valentine195** [comment]
can you please try 7.4.1

**Comment by WychWitch** [comment]
> 
> 
> can you please try 7.4.1

I just tried and!! it works in the table itself but when trying to roll from it it displays a malformed result

The code :

```
| dice: 1d4 | Connections                                         |
| --------- | --------------------------------------------------- |
| 1         | They are associated with `dice: #dnd/factions\|link` |
| 2         | They're from `dice: #dnd/pc\|link`'s past            |
| 3         | They know `dice: #dnd/pc\|link`                      |
| 4         | They know `dice: #dnd/npc\|link`                     |
^connections

`dice: [[NPC Dice Tables#^connections]]`
```

Screenshot:
![image](https://user-images.githubusercontent.com/1291820/142486420-13f56c39-a1af-4f6a-a795-89d48098316a.png)

**Comment by valentine195** [comment]
Okay, I figured out why this is breaking. However, in figuring that out, I also realized that what you're trying to do here won't actually work - the LinkRoller returns the file object, not the link path, so it won't render correctly in the table roller's result.

I will have to work on this a bit, it's a little tricky to get right.

**Comment by WychWitch** [comment]
Ahhh I see!! Thank you for looking into this;;

**Comment by valentine195** [comment]
Please try 7.5.0 - this should work now.

**Comment by WychWitch** [comment]
> Please try 7.5.0 - this should work now.

It does!!! Thank you so much!! This is so exciting aaaaaa
