### ISSUE TITLE
Feature request: dice-mod for tables etc.

### ISSUE THREAD

**Issue by kvndrsslr** [valentine195/obsidian-dice-roller#57]
I was wondering why this feature is not implemented for tables and the like. This would be very handy and more reliable/futureproof than the current saving to plugin data.

**Comment by MythodicalGM** [comment]
Mr. Valentine, I too would love to see this feature. I could create an entire NPC generator within Obsidian if this was possible. As a note, I find myself using a "one and done" roll more than needing to reroll anyway, not sure if I'm in the minority or majority there though. Seeing how the global save feature can be quirky, is dice-mod with |noform (that you graciously added for me) a better long-term option?

I would give you 20 cups of coffee for this, easy. :)

**Comment by valentine195** [comment]
Hi!

This should now be available for all types as of `v7.11.0`.

Deeply nested tables may still be a little wonky with this -- I will work on improving the behavior over the next few days!
