### ISSUE TITLE
keep highest / drop lowest is adding dice instead of dropping

### ISSUE THREAD

**Issue by SlyChameleon** [valentine195/obsidian-dice-roller#6]
I think this may have been broken recently, but as the title says, rolling to keep highest or drop lowest will add the rolls instead.

E.g., dice: 2d20d1 may show [18,9d] and the result is 27 instead of 18.

Similarly, 2d20k, or 2d20k1, do the exact same thing.

![image](https://user-images.githubusercontent.com/86242549/122802690-a4181800-d293-11eb-8e5b-7c9cf2ffaba1.png)

**Comment by valentine195** [comment]
Do you happen to remember if this worked just before the last update?

**Comment by SlyChameleon** [comment]
> Do you happen to remember if this worked just before the last update?

Don't quote me, but I believe about 2-ish weeks ago it was working as expected. Sorry that isn't more exact!

**Comment by valentine195** [comment]
No worries, I'll look into it!

There haven't been many changes between them and now anyway... 😁

**Comment by valentine195** [comment]
Should be fixed in 4.0.4

**Comment by valentine195** [comment]
> It's possible I just need to be more patient, but it seems the plug-in is failing to update, and I wasn't able to install it in a fresh Vault

Nope, my fault - forgot to push the build 😳 

> P.S. - I'm interested in potentially developing an additional TTRG-related plugin (or plugins) for Obsidian, and if you're interested in helping/collaborating/just chatting about it, add me on discord (Kappan#9023). I'd be interested in getting your take on potentially converting some spreadsheet scripting stuff I did to make it work in Obsidian, and I'd be happy to help with any further work you might be doing on your current plugins.

I'd love to! Added 😄
