### ISSUE TITLE
Feature Request: Specify the Heading Level

### ISSUE THREAD

**Issue by zcysxy** [valentine195/obsidian-dice-roller#60]
Thanks for this marvelous and powerful plugin! I have a small FR and I don't know if it's reasonable.

When using Dice Roller to return headings, I would like to specify the heading level. For example, I use H2 to group different classes of questions, and use H3 to present questions. When I want to get some random questions, I want the returned headings to be H3 rather than H2 or H1.

**Comment by valentine195** [comment]
Hi, this has been added in 7.9.0:

`` `dice: [[Note]]|heading-2` ``
