### ISSUE TITLE
Saves not working as expected- rolling on tables

### ISSUE THREAD

**Issue by scarfur** [valentine195/obsidian-dice-roller#65]
Hey there,

first of all thank you for this great plugin!

I tried using rolls on one column tables via `dice+: [[note#^table]]`. Global saves off. So far so good.

It seems on closing obsidian or the note with the roll result, the results are not permanent. Neither they are when I jump in edit mode and change something (keystroke) in the same paragraph.

Is there anything I could have done wrong or to fix that? Maybe a bug?

Many thanks in advance!

**Comment by valentine195** [comment]
I’ll take a look - sometimes saving results just doesn’t work. It’s a little tricky to figure out which result goes with which roller on a page.

**Comment by scarfur** [comment]
**After testing some cases, I found more you maybe could fix too (really hope so <3):**
* closing and reopening obsidian still reroll table results with syntax `dice+: [[note#^table]]` while number results (eg syntax: `dice+: 1d6`) are permanent as expected
* changing a single character in the same paragraph as `dice+: [[note#^table]]` results in a reroll
