### ISSUE TITLE
[Bug] d100 Dice doesn't follow the same styling as the other dice

### ISSUE THREAD

**Issue by SlRvb** [valentine195/obsidian-dice-roller#66]
The d100 dice doesn't follow the same structure as the other dice resulting in the `%` symbol disappearing when recoloring the svgs.

---

The other dice are structured like so:
```
svg
    g "Shapes"
        path .cls-1
    g "Layer_1"
```
![Obsidian_3LOCEfvoMv](https://user-images.githubusercontent.com/54087190/147791828-17a19a93-b9b7-4a01-939f-74cbe8796b1b.png)

Where as d100 is structured like:
```
svg
    g "Layer_1"
         circle .cls-1
```

![Obsidian_AzADBmVFzm](https://user-images.githubusercontent.com/54087190/147791993-17df7245-8547-4cb5-90aa-4fcfa392c7b6.png)

**Comment by valentine195** [comment]
Fixed in 7.11.1
