### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by mhofherr** [valentine195/obsidian-dice-roller#7]
Hi there,

thanks for this plugin, I started to integrate it into my Fantasy AGE campaign, managed via Obsidian. For GM-ing am currently switching from my MacBook to my iPad Pro (Obsidian Mobile Beta). When trying to enable it on Obsidian Mobile I get the message that the plugin does not support Mobile. Would it be possible to enable that?

Thanks,
Matthias

**Comment by valentine195** [comment]
I don't think there's anything in the plugin that would prevent from working on mobile. I had it set to desktop only because I don't have the mobile app and couldn't test it.

I just set it to be allowed on desktop - if you try to install it, let me know if you run into any errors.

**Comment by mhofherr** [comment]
Thanks. Now I can install it, but it is impossible to enable via GUI. Will check on weekend if I can force activation via editing some config file.

**Comment by valentine195** [comment]
Okay, in that case it is possible that a module in the plugin is causing it to not work on mobile. I'll have to dig through what's installed to see if anything could be doing it, but I won't be able to debug unfortunately.

**Comment by mhofherr** [comment]
So, just invested 5 minutes in testing. I added it manually to file "community-plugins.json" in my mobile config and it was enabled afterwards. Some simple tests worked, so everything seems to be fine. Don't know why I have to manually enable it, but for now I'm good.
Thanks,
Matthias

**Comment by valentine195** [comment]
Well, thanks for investigating! Kind of bizarre, but glad it works.

**Comment by valentine195** [comment]
According to the discord, this was because I forgot to push a new release (whoops 😳). Should be able to enable from the GUI now.
