### ISSUE TITLE
Allow inline switching of dice graphics

### ISSUE THREAD

**Issue by apolaine** [valentine195/obsidian-dice-roller#70]
For many rolls it's useful to have the dice graphics displayed, but for some generators drawing from lists, I'd like to have it turned off. It would be great to be able to specify that argument inline. Something like this:

`
dice: [[note^list]]Item display: none;
`

**Comment by valentine195** [comment]
Are you talking about the dice icon? They can be turned off by appending `|nodice` to the roll.

**Comment by apolaine** [comment]
I was. I should read the documentation. :-)
