### ISSUE TITLE
Concatenate multiple table rolls

### ISSUE THREAD

**Issue by apiarian** [valentine195/obsidian-dice-roller#75]
Is there a way to concatenate or combine multiple tables rolls?

```
| items |
| ----- |
| spoon |
| twig  |
| bowl  |
| hat   |
^items

| spells   |
| -------- |
| light    |
| darkness |
| fireball (self)         |
^spells

hags item: `dice: 3d([[dice test#^items]] + [[dice test#^spells]])`
```

**Comment by apiarian** [comment]
the underlying usecase here is generating a list of things by combining a bunch of elements, then manually filtering that list down to a set that seems actually interesting, tweaking, and otherwise refining the list into something actually usable. so as an initial imagination ignition tool

**Comment by valentine195** [comment]
> Is there a way to concatenate or combine multiple tables rolls?

In this case, I recommend just making two separate rollers:
```md
| items |
| ----- |
| spoon |
| twig  |
| bowl  |
| hat   |
^items

| spells   |
| -------- |
| light    |
| darkness |
| fireball (self)         |
^spells

hags item: `dice: 3d[[testing#^items]]`  `dice: [[testing#^spells]]`
```

> poking around some more, it seems that the table dice parsing eats all the things after the double-bracket link bit into the header. things like noform, parentheses around the double-bracket link, or other things don't seem to be parsing correctly

Thanks, I will work to improve my regex around this.

**Comment by apiarian** [comment]
yup, i've ended up splitting the queries. it works well enough, though it's a bit slower. i guess i could have a pane with something like 3d-table1 and 3d-table2 and then another pane where i could record the combinations that seem interesting.

**Comment by apiarian** [comment]
oh! and i could write up a bunch of rows like that with a reroll button!

**Comment by valentine195** [comment]
Yep! And use the `|nodice` flag to make them seem like one roll 😁

I have spent some time thinking about combinators like this, but haven’t had the time to sit and play with it.
