### ISSUE TITLE
Fantasy AGE Stunt Die

### ISSUE THREAD

**Issue by mhofherr** [valentine195/obsidian-dice-roller#8]
Hi Jeremy,

I am using the Fantasy AGE system, which basically uses 3d6 for skill rolls. Additionally it has the concept of a "Stunt Die":
If you roll doubles, it is called a Stunt. This generates 1-6 stunt points, the amount depending on one of the three thrown dice, the "Stunt Die". The Stunt Die is a fixed one (usually marked by choosing a die with a different color).
Would it be possible to support this behaviour (detecting a Stunt and showing the number of stunt points) in Dice Roller?

Thanks,
Matthias

**Comment by valentine195** [comment]
Yes, absolutely. I don't have any experience with this system so I need to wrap my head around how it works, but should be able to get this out within a day or so.

**Comment by valentine195** [comment]
Let me see if I understand correctly:

1. You ALWAYS roll 3d6 for the stunts
2. One of the 3d6 is the stunt die. 
3. If you roll doubles with the other two, you get stunt points equal to the stunt die. 

Is that correct?

I'm thinking the syntax will be `XdS` (similar to percent or Fudge/Fate dice rolls), and it'll roll 3d6 X times and display the results as something like `[3, 3, 4S]` or `[4, 2, 0S]`. 

Does that seem like it would work for you?

**Comment by mhofherr** [comment]
1: You ALWAYS roll 3d6 for any **skill test**
2: One of the 3d6 is the stunt die.
3: If you roll doubles with **any of the three**, you get stunt points equal to the stunt die (if the skill roll succeeds, but that is beyond Dice Roller)

This means, output should be something like (provided that first die is the stunt die):
- [3, 2, 4]
- [3, 4, 4] - Stunt with 3 Stunt Points
- [6, 6, 6] - Stunt with 6 Stunt Points

Since this is also a skill test, the normal result of the 3d6 should be displayed as usual.

**Comment by valentine195** [comment]
Gotcha. Since you say you choose the stunt die, would this also happen?

- [3, 4, 3] - Stunt with 3 stunt points

**Comment by mhofherr** [comment]
Stunt Die is usually fixed. With real dice, you choose one who has a different color. For Dice Roller, I propose to make the first one the "fixed one".

**Comment by valentine195** [comment]
Yep, I just wanted to make sure that you didn't get the "non-double" dice as the stunt points. Basically, you'll always get the first die's result as stunt points if _any_ combination of doubles occurs.

**Comment by mhofherr** [comment]
Yes, exactly

**Comment by valentine195** [comment]
Please try 4.1.0 and let me know if it works well for you.

See [here](https://github.com/valentine195/obsidian-dice-roller#fantasy-age-stunt-dice) for the syntax.

**Comment by mhofherr** [comment]
Works like a charm, thank you very much!

Is "Stunt dice cannot be used with modifiers. Any modifiers supplied will be ignored" a technical limitation or is this based on my description? Adding a modifier would be great, if possible (Fantasy AGE allows to add skill point to such rolls).

**Comment by valentine195** [comment]
It's a semi-technical difficulty - just way easier to implement this way. I'll try to think of a better way to do it if you do need some modifiers.

**Comment by mhofherr** [comment]
That would be really great. But - no pressure - this is not super-urgent.

**Comment by valentine195** [comment]
Stunt dice can now be used in formulas and have modifiers in 5.1.2. 

Sorry this took so long!

**Comment by mhofherr** [comment]
Tested, worked without problems.
Thanks, much appreciated!
