### ISSUE TITLE
Not seeing return of multiple elements  from a two-column table

### ISSUE THREAD

**Issue by shepster** [valentine195/obsidian-dice-roller#81]
It seems with a two-column table the returning of multiple elements isn't working

```
| dice: 1d6 | item |
| --- | --- |
| 1-3 | Common |
| 4,5 | Rare |
| 6   | Unique |

^item

Should be two: `dice: 2d[[testing#^item]]`
```

I do not see two random items pulled from the table. Normally in the format: **item||item** :game_die:

**Comment by JYCasalis** [comment]
@shepster 
Should be fixed with version 8.5.0
