### ISSUE TITLE
[Feature Request]Dice roller blocks by tag or keyword

### ISSUE THREAD

**Issue by Quorafind** [valentine195/obsidian-dice-roller#9]
If you want to combine dataview api with dice roller, the new feature could be stronger that because I have many notes tagged the same tag, and they are in same topic.

I think it will be nice to have a `dice: 1d#tag` or `dice: 1d|Keyword`, which will be fantastic for me.

**Comment by valentine195** [comment]
Just to be clear, #tag would look at multiple files at the same time, right?

**Comment by Quorafind** [comment]
@valentine195 Yep, one block from multiple files(random twice?), is it doable?

**Comment by valentine195** [comment]
Ohh okay, so not random from EITHER file, but a separate result from BOTH (or however many). Basically, same as making multiple dice rollers. 

Should be doable, let me do some testing.

**Comment by valentine195** [comment]
Hi, 5.1.0 added this feature. Please see [the Readme](https://github.com/valentine195/obsidian-dice-roller#tags).
