### ISSUE TITLE
[Feature Request] An option to not roll the dice until the button is clicked?

### ISSUE THREAD

**Issue by ColColonCleaner** [valentine195/obsidian-dice-roller#98]
There is already an option to disable showing the formulas, but can there be an option to avoid showing any rolled number until the dice button is clicked?

For example in the below image all of the dice values are already rolled whenever I open the page. Is there a way to disable this pre-rolling and only show a result number when the dice button is pressed?

![image](https://user-images.githubusercontent.com/1903507/167271091-d78d8829-d154-40e7-96c4-2cc6c3c8cd17.png)

This section in source mode.

![image](https://user-images.githubusercontent.com/1903507/167271113-21ada92b-a309-4a6b-af87-6bfd5eba6496.png)

**Comment by valentine195** [comment]
Closed by PR #105
